config/routes.rb
Rails.application.routes.draw do
  get 'managers/index'
  get 'addresses/index'
  get 'settings/index'
  get 'project_managements/index'
  get 'employees/index'
  get 'designations/index'
  get 'leave_types/index'
  get 'projects/index'
  get 'holidays/index'
  get 'employee_details/index'
  devise_for :employees
  #get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
resources :holidays
resources :leave_types
resources :designations
resources :projects
resources :employees
resources :project_managements
resources :settings
resources :employee_details
resources :addresses
resources :managers

  # Defines the root path route ("/")
  root "home#index"

  get 'administration',to: 'home#administration'

  get 'dash',to: 'home#dash'

  get 'leave',to: 'home#leave'
  
  get 'attendance',to: 'home#attendance'

  get 'setting',to: 'home#setting'

  get 'employeeadmin',to: 'home#employeeadmin'

  get 'projectadmin',to: 'home#projectadmin'

  get 'hr',to: 'home#hr'
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :employee 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :employee
end

app/models/designation.rb
class Designation < ApplicationRecord
    #has_many: :employees, :through => :employee_details
end

app/models/employee.rb
class Employee < ApplicationRecord
  paginates_per 2
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :employee_detail
  has_one :address
  has_many :attendances
  has_many :employee_leaves
  #has_many :leaves, :through=> :employee_leaves
  has_one :designation, :through=> :employee_detail
  #has_many :employee_projects
  #has_many :projects, :through=> :employee_projects
  #belongs_to :role
  has_and_belongs_to_many :projects

  def is_admin?

    self.role && self.role.name == 'administration'
    
    end
    
    def full_name
    
    fn = self.first_name || 'administration'
    
    ln = self.last_name || ''
    
    fn.capitalize + ln.capitalize
    
    end
    
    
    
    def profile_name
    
    fn = self.first_name || 'administration'
    
    ln = self.last_name || ''
    
    return fn.chr.capitalize + ln.chr.capitalize
    
    end
end

app/models/employee_detail.rb
class EmployeeDetail < ApplicationRecord
    belongs_to :employee
    belongs_to :designation
end

app/models/employee_leave.rb
class EmployeeLeave < ApplicationRecord
    #belongs_to :employee
    #has_one :leave
end

app/models/employee_project.rb
class EmployeeProject < ApplicationRecord
    #belongs_to :employee 
    #belongs_to :project 
end

app/models/holiday.rb
class Holiday < ApplicationRecord
end

app/models/leave.rb
class Leave < ApplicationRecord
    has_many :employee_leaves
end

app/models/leave_type.rb
class LeaveType < ApplicationRecord
    has_many :employee_leave
end

app/models/project_management.rb
class ProjectManagement < ApplicationRecord
    # has_many: employees
    #has_many :employee_projects
    #has_many :employees, :through=> :employee_projects
    #has_and_belongs_to_many :employees
end

app/models/role.rb
class Role < ApplicationRecord
   # has_many :employees
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  before_action :set_holiday, only: [:edit, :update, :destroy]
  def index
    @holidays = Holiday.all
  end
  def new
    @holiday = Holiday.new
  end

  def create
    @holiday = Holiday.new(holidays_params)
    if @holiday.save 
      redirect_to holidays_path
    else  
      render 'new'
    end
  end

  def edit
    

  end

  def update 
    if @holiday.update(holidays_params)
      redirect_to holidays_path
    else  
      render 'edit'
    end
  end

  def destroy
    @holiday.destroy 
    redirect_to holidays_path
  end
  private 

  def holidays_params 
    params.require(:holiday).permit(:name, :date, :year)
  end

  def set_holiday 
    @holiday = Holiday.find(params[:id])
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leave_types_helper.rb
module LeaveTypesHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/holidays/_form.html.erb
<%= form_with model:@holiday do |f| %>
  
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_field :date, autofocus: true, autocomplete: "description" %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.text_field :year %>
  </div><br>
  
 
  <div class="actions admin-add-cancel-buttons-container">
    <%= f.submit "Save", class: "btn btn-primary" %>
    <%= link_to "Cancel", holidays_path, class: "btn btn-danger" %>
  </div>
  
<% end %>

app/views/holidays/_remote_modal.html.erb
<%= turbo_frame_tag "remote_modal" do %>

    <div class="modal fade" id="shareRecipeModal" tabindex="-1" aria-labelledby="newItemRemoteModalLabel" aria-hidden="true" data-controller="remote-modal" data-action="turbo:before-render@document->remote-modal#hideBeforeRender">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content" id="modal_content">
                <div class="modal-header">
                    <h4 class="modal-title" id="newItemRemoteModalLabel"><%= title %></h4>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body remote_modal_body" id="remote_modal_body">
                    <%= yield %>
                </div>
            </div>
        </div>
    </div>

<% end %>

app/views/holidays/edit.html.erb
<div class="d-flex flex-row ">
    <%= render 'layouts/dashadmin'%>
        <div class="d-flex flex-column">
            <div class="c4">
            <center>
                <h1 class="admin-management-heading">Holidays Management</h1>
                <%= render "remote_modal", title: "Edit Holiday" do %>
                <%= render "form", holiday: @holiday %>
                <% end %>
            </center>
            </div>
        </div>
</div>

app/views/holidays/index.html.erb
<div class="d-flex flex-row ">
    <%= render 'layouts/dashadmin'%>
        <div class="d-flex flex-column">
            <div class="c4">
                <center>
                <h1 class="admin-management-heading">Holidays Management</h1>
                </center>
                <div class="w-100">
                <table class="table">
                    <tr class="t-header-cotainer">
                        <th>Holiday Name</th>
                        <th>Holiday Date</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                    <% @holidays.each do |holiday| %>
                        <tr class="t-sub-container">
                            <td>
                            <%= holiday.name %>
                            </td>
                            <td>
                            <%= holiday.date %>
                            </td>
                            <td>
                                <%= link_to edit_holiday_path(holiday), class: "btn" , data: { turbo_frame: "remote_modal" } do %> 
                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
                                <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"/>
                                </svg>
                                <% end %>
                            </td>   
                            <td>
                                <%= button_to holiday_path(holiday),  class: "btn", method: :delete do %>
                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                </svg>
                                <% end %>
                            </td>
                        </tr>
                    <% end %>
                </table>
                <div>
                    <%= link_to "Add New Holiday", new_holiday_path, method: :get, data: { turbo_frame: "remote_modal" }, class: "btn btn-primary" %>  
                </div>
            </div>
        </div>
</div>

app/views/holidays/new.html.erb
<div class="d-flex flex-row ">
    <%= render 'layouts/dashadmin'%>
        <div class="d-flex flex-column">
            <div class="c4">
                <center>
                <h1 class="admin-management-heading">Holidays Management</h1>
                <%= render "remote_modal", title: "New Holiday" do %>
                <%= render "form", holiday: @holiday %>
                <% end %>
                </center>
            </div>
        </div>
</div>