config/routes.rb
Rails.application.routes.draw do
  get 'managers/index'
  get 'addresses/index'
  get 'settings/index'
  get 'project_managements/index'
  get 'employees/index'
  get 'designations/index'
  get 'leave_types/index'
  get 'projects/index'
  get 'holidays/index'
  get 'employee_details/index'
  devise_for :employees
  #get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
resources :holidays
resources :leave_types
resources :designations
resources :projects
resources :employees
resources :project_managements
resources :settings
resources :employee_details
resources :addresses
resources :managers

  # Defines the root path route ("/")
  root "home#index"

  get 'administration',to: 'home#administration'

  get 'dash',to: 'home#dash'

  get 'leave',to: 'home#leave'
  
  get 'attendance',to: 'home#attendance'

  get 'setting',to: 'home#setting'

  get 'employeeadmin',to: 'home#employeeadmin'

  get 'projectadmin',to: 'home#projectadmin'

  get 'hr',to: 'home#hr'
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :employee 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :employee
end

app/models/designation.rb
class Designation < ApplicationRecord
    #has_many: :employees, :through => :employee_details
end

app/models/employee.rb
class Employee < ApplicationRecord
  paginates_per 2
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :employee_detail
  has_one :address
  has_many :attendances
  has_many :employee_leaves
  #has_many :leaves, :through=> :employee_leaves
  has_one :designation, :through=> :employee_detail
  #has_many :employee_projects
  #has_many :projects, :through=> :employee_projects
  #belongs_to :role
  has_and_belongs_to_many :projects

  def is_admin?

    self.role && self.role.name == 'administration'
    
    end
    
    def full_name
    
    fn = self.first_name || 'administration'
    
    ln = self.last_name || ''
    
    fn.capitalize + ln.capitalize
    
    end
    
    
    
    def profile_name
    
    fn = self.first_name || 'administration'
    
    ln = self.last_name || ''
    
    return fn.chr.capitalize + ln.chr.capitalize
    
    end
end

app/models/employee_detail.rb
class EmployeeDetail < ApplicationRecord
    belongs_to :employee
    belongs_to :designation
end

app/models/employee_leave.rb
class EmployeeLeave < ApplicationRecord
    #belongs_to :employee
    #has_one :leave
end

app/models/employee_project.rb
class EmployeeProject < ApplicationRecord
    #belongs_to :employee 
    #belongs_to :project 
end

app/models/holiday.rb
class Holiday < ApplicationRecord
end

app/models/leave.rb
class Leave < ApplicationRecord
    has_many :employee_leaves
end

app/models/leave_type.rb
class LeaveType < ApplicationRecord
    has_many :employee_leave
end

app/models/project_management.rb
class ProjectManagement < ApplicationRecord
    # has_many: employees
    #has_many :employee_projects
    #has_many :employees, :through=> :employee_projects
    #has_and_belongs_to_many :employees
end

app/models/role.rb
class Role < ApplicationRecord
   # has_many :employees
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/layouts/_dash.html.erb
<div class="d-flex flex-row ">
    <div class="d-flex flex-column">
        <div>
            <%= button_to "Dashboard", dash_path, class: "box", method: :get%>
        </div>
        <div>
            
            <%= button_to "Leaves", leave_path, class: "box", method: :get%>
        </div>
        <div>
            <%= button_to "Attendance", attendance_path, class: "box", method: :get%>
        </div>
        <div>
            <%= button_to "Settings", employee_details_path, class: "box", method: :get%>
        </div>
    </div>
</div>

app/views/layouts/_dashadmin.html.erb
<div class="d-flex flex-row ">
    <div class="d-flex flex-column">
    
        <div>
            <%= button_to "Leaves Management", leave_types_path, class: "box", method: :get%>
        </div>
        <div>
            
            <%= button_to "Designation Management", designations_path, class: "box", method: :get%>
        </div>
        <div>
            <%= button_to "Employees Management", employees_path, class: "box", method: :get%>
        </div>
        <div>
            <%= button_to "Holidays Management", holidays_path, class: "box", method: :get%>
        </div>
        <div>
            <%= button_to "Project Management", project_managements_path, class: "box", method: :get%>
        </div>
    </div>
</div>

app/views/layouts/_dashmanager.html.erb
<div class="d-flex flex-row ">
    <div class="d-flex flex-column">
    
        <div>
            <%= button_to "Team Mates", leave_types_path, class: "box", method: :get%>
        </div>
        <div>
            
            <%= button_to "Projects", designations_path, class: "box", method: :get%>
        </div>
        <div>
            <%= button_to "Leave Approval", employees_path, class: "box", method: :get%>
        </div>
        <div>
            <%= button_to "Attendance Correction", holidays_path, class: "box", method: :get%>
        </div>
        
    </div>
</div>

app/views/layouts/_footer.html.erb
<!-- Footer -->
  <footer class="page-footer font-small blue">

   <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2020 Copyright:
      <a href="/"> Zensark.com</a>
    </div>
  <!-- Copyright -->

  </footer>
  <!-- Footer -->

app/views/layouts/_messages.html.erb
    
    

<% if notice%>
    <p class="notice"><%= notice %></p>
<% end%>

<% if alert%>
    <p class="alert"><%= alert %></p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar">
    <div class="container-fluid">
    <a class="" href="#">
      <img src="https://zensark.com/zensark2/wp-content/uploads/2021/01/Asset-16.png" alt="" width="150" height="50">
    </a>
    <% if current_employee %>
        <div class="dropdown">
            <button class="custom-profile-button" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                <img src="https://www.w3schools.com/howto/img_avatar2.png" alt="Avatar" class="avatar">  
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li><%= button_to "Administration", administration_path, class: "dropdown-item", method: :get%></li>
                <li><%= button_to "Manager", managers_index_path, class: "dropdown-item", method: :get%></li>
                <li><%= button_to "Logout", destroy_employee_session_path, class: "dropdown-item", method: :delete%></li>
            </ul>
        </div>
    <%else%>
        <% if request.path.include? "sign_in"%>
        <%= button_to "Home", root_path, class: "b1", method: :get %>
        <%else%>
        <%= button_to "Sign In", new_employee_session_path, class: "b1", method: :get %>
        <%end%>
    <%end%>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HRMS</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags("application") %>
  </head>

  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= render 'layouts/navbar'%>
    <%= render 'layouts/messages'%>
    
    <div class="row">
    <%= yield %>
    <%= turbo_frame_tag "remote_modal", target: "_top" %>
    </div>
    
  </body>
</html>